import Link from "next/link";
import type { Metadata } from "next";
import { DocsShell } from "@/components/navigation/DocsShell";

export const metadata: Metadata = { title: "Version history" };

export default function VersionHistoryPage() {
  return <DocsShell active="Version history"><div className="max-w-4xl"><p className="eyebrow mb-4">Documentation / version history</p><h1 className="text-4xl font-extrabold tracking-[-0.04em] md:text-6xl">Version history</h1><p className="body-copy mt-5 text-lg">A short record of how DS by Berit has been shaped over time. Entries are updated manually when a meaningful design-system milestone is complete.</p><div className="mt-12 space-y-5"> 

    <article className="rounded-2xl border border-[var(--color-border-default)] bg-[var(--color-surface-subtle)] p-6"><div className="flex flex-wrap items-baseline justify-between gap-3"><p className="eyebrow m-0">2026-09-15</p><span className="token-name">Naming and tokens</span></div><h2 className="mt-4 text-2xl font-bold">Named every variant and stopped repeating colour values</h2><p className="body-copy mt-3">Examples used to show several versions of a component side by side without saying which was which. You had to read the code tab to find out that the first button was the primary one. Every variant now carries its name above it, set in IBM Plex Mono so it reads as a label about the example rather than as part of it. Where the name was previously written inside the preview, such as a card whose only text was &quot;Hover state&quot;, the preview now shows realistic content instead and the label does the naming.</p><p className="body-copy mt-3">The Light and Dark preview panels were defining their colours by repeating hex codes that already existed as variables a few lines above, and the code behind the panels repeated the same list a third time. Both now point at the variables. Nothing changed on screen; the values simply live in one place now. Four colours that were in use but undocumented were added to the token reference, and the spacing and shape pages now show their semantic tokens the way the colours page already did.</p><p className="body-copy mt-3">The system also had two names. It is called DS by Berit, but an earlier name, Fieldwork, was still sitting in the landing page, the foundations intro, this page and a few examples. The pages that talk about the system now say DS by Berit. In the mock-ups, where the old name was only ever standing in for a customer&apos;s product, it has been replaced with ordinary sample content.</p></article>
    
    <article className="rounded-2xl border border-[var(--color-border-default)] bg-[var(--color-surface-subtle)] p-6"><div className="flex flex-wrap items-baseline justify-between gap-3"><p className="eyebrow m-0">2026-09-14</p><span className="token-name">Documentation and rules</span></div><h2 className="mt-4 text-2xl font-bold">Wrote the project rules</h2><p className="body-copy mt-3">Added AGENTS.md, defining how the system is built: folder structure, 
the spacing scale, the rule against hardcoding values that exist as 
variables, accessibility requirements, and what needs checking before 
it gets changed. Until now these rules existed only in the code itself, 
which meant every session started by guessing them.</p><p className="body-copy mt-3">Read through the system and fixed what did not match. Removed a font 
that was being loaded but never used, corrected spacing values that 
fell outside the documented scale, and added README files explaining 
the components and token folders.</p></article>
    
    <article className="rounded-2xl border border-[var(--color-border-default)] bg-[var(--color-surface-subtle)] p-6"><div className="flex flex-wrap items-baseline justify-between gap-3"><p className="eyebrow m-0">2026-09-10</p><span className="token-name">Foundation release</span></div><h2 className="mt-4 text-2xl font-bold">Established the documentation system</h2><p className="body-copy mt-3">Created the standalone Next.js project, token foundation, documentation shell, landing page, Getting started flow, Foundations catalog, Components index, and four accessible component families: Navigation, Buttons, Cards, and Table.</p><p className="body-copy mt-3">Added practice pages for project management and analytics, responsive desktop/mobile mock-ups, component modes, compound table parts, navigation micro-components, code tabs, Light/Dark previews, accessibility improvements, and color-token swatches.</p></article>
  
  </div><div className="mt-10 rounded-2xl bg-[var(--color-surface-inverse)] p-6 text-white"><p className="eyebrow text-[var(--color-action-accent)]">Maintenance note</p><p className="mt-3 text-white/75">Entries are added as the system develops, grouped by day. This is a public record of how the system has changed, not a technical changelog..</p><Link href="/getting-started" className="mt-5 inline-flex rounded-full bg-[var(--color-action-accent)] px-4 py-3 text-sm font-semibold text-[var(--color-content-primary)]">Back to getting started <span aria-hidden="true" className="ml-1">→</span></Link></div></div></DocsShell>;
}
